# Run jazzy from the current directory to generate documentation.

module: 'LOC8'
module_version: '0.1.0'
author: 'Marwan Al Masri'
author_url: 'http://marwan-al-masri.github.io/LOC8'
copyright: 'Copyright © 2017 LOC8. All rights reserved.'
github_url: 'https://github.com/Marwan-Al-Masri/LOC8'
min_acl: 'private'
output: 'docs'
docset_icon: './icon.png'
documentation: 'Documentation/*.md'
theme: 'fullwidth'
hide_documentation_coverage: true
skip_undocumented:  true
clean: false

exclude:
    - 'LOC8/UI'
    - 'LOC8/Graphics'
    - 'LOC8/Constants and Extensions'
    - 'LOC8 App'

custom_categories:
  - name: 'Guides'
    children:
    - 'Fundamentals'
    - 'Development'
  - name: 'Geometry'
    children:
    - 'Geometry'
    - 'NumericalIntegration'
    - 'Angle'
    - 'EulerAngles'
    - 'RotationMatrix'
    - 'Quaternion'
    - 'Rotation3D'
    - 'CartesianVector'
    - 'SphericalVector'
    - 'CylindricalVector'
    - 'Vector3D'
    - 'Direction'
  - name: 'Physics'
    children:
    - 'Physics'
    - 'Measurement'
    - 'Acceleration'
    - 'Velocity'
    - 'Distance'
    - 'Accuracy'
    - 'MagneticField'
    - 'Heading'
    - 'Motion'
    - 'MotionActivityStatus'
    - 'MotionActivity'

  - name: 'Models'
    children:
    - 'FilterType'
    - 'Filter'
    - 'AccelerationFilter'
    - 'EstimationHandler'
    - 'Estimation'
    - 'TrackingSession'
    - 'LogLevel'
    - 'LogRecord'

  - name: 'Managers and Services'
    children:
      - 'Log'
      - 'MotinDetector'
      - 'SensorsManager'
      - 'MultipeerManager'
      - 'SettingsService'
