# Run jazzy from the current directory to generate documentation.

module: 'LOC8'
author: 'LOC8'
# author_url: https://www.LOC8.com
copyright: Copyright © 2017 LOC8. All rights reserved.'
github_url: 'https://github.com/Marwan-Al-Masri/LOC8'
min_acl: 'public'
output: 'docs'
skip_undocumented: true
clean: true
docset_icon: 'Icon.png'
exclude: 'LOC8/UI, LOC8/Graphics, LOC8/Helpers, LOC8/LOC8/Constants\ and\ Extensions'
# theme: fullwidth

# custom_categories:
#     - name: Geometry & Physics
#       children:
#       - Radian
#       - Degree
#       - CartesianVector
#       - PolarVector
#       - Vector3D
#       - EulerAngles
#       - RotationMatrix
#       - Quaternion
#       - Rotation3D
#       - Physics
#       - Measurement
#       - Acceleration
#       - Velocity
#       - Distance
#     - name: Models
#       children:
#         - Filter
#         - FilterType
#         - AccelerationFilter
#         - Direction
#         - Heading
#         - MotionActivityConfidence
#         - MotionActivityStatus
#         - MotionActivity
#         - EstimationHandler
#         - Estimation
#         - TrackingSession
#     - name: Generic
#       children:
#       - degreesToRadians
#       - degreesToRadians
#       - clamp
#       - wrap
#       - ^
#       - ~
