codecov:
  notify:
    require_ci_to_pass: true

coverage:
  precision: 2
  range: 80...100
  round: up
  ignore:
    - "LOC8Tests/*"
    - "Documentation/*"
    - "docs/*"
    - "LOC8/Graphics/*"
    - "LOC8/UI/*"

status:
  project: yes
  patch: no
  changes: no

comment:
  layout: "header, diff, changes"
